// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParaTest.Models.Cityzen;

#nullable disable

namespace ParaTest.Migrations
{
    [DbContext(typeof(CityzenDbContext))]
    [Migration("20220823085447_InitialCityzen_WO_Seeder")]
    partial class InitialCityzen_WO_Seeder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("cityzen_id_seq", "registry")
                .StartsAt(1000L);

            modelBuilder.Entity("ParaTest.Models.Cityzen.Cityzen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR registry.cityzen_id_seq");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birth_date");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("death_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(747)
                        .HasColumnType("nvarchar(747)")
                        .HasColumnName("full_name");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("SNILS")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FullName" }, "cz_birth_date");

                    b.HasIndex(new[] { "FullName" }, "cz_death_date");

                    b.HasIndex(new[] { "FullName" }, "cz_full_name");

                    b.HasIndex(new[] { "INN" }, "cz_inn_uq")
                        .IsUnique();

                    b.HasIndex(new[] { "SNILS" }, "cz_snils_uq")
                        .IsUnique();

                    b.ToTable("cityzen", "registry");
                });
#pragma warning restore 612, 618
        }
    }
}
